### ISSUE TITLE
How to make wlr-foreign-toplevel-management work?

### ISSUE THREAD

**Issue by ilya-fedin** [wmww/mirco#1] opened 2021-08-20 02:09 UTC
I'm trying mirco + mate-panel on Arch since 1.24, but it still doesn't work, even with 1.26... It displays the panels, but I don't see the list of opened windows even though I see the code for it is in place. I have a VM with Ubuntu MATE and mate-wayland snap and I see it works with it, but I can't make it work with manually built mirco and mate-panel from the community repo on Arch. :(

Maybe libmir reads some file with whitelist of binaries that allowed to use wlr-foreign-toplevel-management and I should fill it? Or some other voodoo magic is required?

**Comment by wmww** [comment] 2021-08-20 17:08
I believe the problem is that on Arch the applets are being built out-of-process, which does not work on Wayland. Trying to make out-of-process applets work on Wayland is a large technical undertaking, and the consensus was generally that it provides little or no benefit. Even so, it seems mate [still builds them out-of-process by default](https://github.com/mate-desktop/mate-panel/blob/bf36bbf8012e3036fd75555e89acbd65aaa8bb78/configure.ac#L115) and [the Arch package does not override that](https://github.com/archlinux/svntogit-community/blob/150201a044a6798ec24ae6a832906196d4bb3c59/trunk/PKGBUILD#L21). Therefore some applets (such as the window list) will not work on Wayland on the pre-built mate-panel on Arch.

[this](https://github.com/wmww/personal/tree/master/repos/mate-panel) is where I keep track of how to build and run mate-panel locally and [here](https://github.com/wmww/personal/blob/a3b6ca667a254e83c086c0f39bab53db83dfa43c/repos/mate-panel/run_autogen.sh#L18) is where I enable in-process applets. If you build from source with in-process applets and it still doesn't work, you may also have to re-add the window list to the panel.

Closing, as I doubt this is a problem with Mirco. Feel free to poke mate-panel upstream or the Arch package, but my involvement is currently minimal so I won't be doing that at this time.

**Closed as completed by wmww** 2021-08-20 17:08 UTC

**Comment by ilya-fedin** [comment] 2021-08-20 17:31
Wow, thanks, it works! I feel like I should have asked earlier (I tried to start a talk about Wayland on #mate on freenode multiple times, but got no answer each time), I lost a lot of time :D

**Comment by ilya-fedin** [comment] 2021-10-07 16:26
@wmww hi, I have a question... I tried multiple third-party applets and all of them seem to fail with `Requested out-of-process applet, which is only supported on X11`, does that mean third-party applets will never be supported? Or they can be compiled in-process as well?

**Comment by wmww** [comment] 2021-10-09 20:27
I believe it should be possible to compile them in. It might even be possible to compile them without recompiling mate-panel, and then have mate-panel dynamically load the .so in-process. I haven't messed with mate-panel in a while, so I can't say for sure.

**Comment by ilya-fedin** [comment] 2021-10-09 20:48
:(
I wanted to try to use the mate-indicator applet or the xapps applet, both of them provide support for SNI tray.
btw, is there a way to take a screenshot on mirco? I see some graphic artifacts on mate-panel and with gtk-layer-background I would like to report, but I this wouldn't be simple without screenshots :D

**Comment by wmww** [comment] 2021-10-12 16:52
You can't currently take a screenshot directly. If you run Mirco from within another desktop environment it will run inside it, and you can take a screenshot from the host.

**Comment by ilya-fedin** [comment] 2021-10-12 17:04
it's a pity :(
Does Mir support wlr-screencopy? Maybe I can enable it via miral::WaylandExtensions and use wlroots utilities?

**Comment by wmww** [comment] 2021-10-14 22:35
No, Mir does not support wlr-screencopy at this time

**Comment by ilya-fedin** [comment] 2021-10-14 23:07
:(
Thanks for the info

**Comment by ilya-fedin** [comment] 2022-01-27 14:04
> I believe it should be possible to compile them in. It might even be possible to compile them without recompiling mate-panel, and then have mate-panel dynamically load the .so in-process.

That should work with applets written in C, but what to do with python applets? :thinking:

**Comment by wmww** [comment] 2022-01-27 17:12
I have no idea how python applets integrate with mate-panel. Might be a way to run them in-process, might not.

**Comment by ilya-fedin** [comment] 2022-04-01 19:45
I finally got some screenshots with kmsgrab. I see multiple graphical artifacts:
1. The top panel doesn't have background. Should I report this to gtk-layer-background or to mate-panel?
2. Task switcher doesn't seem to honor theme, looks like it always uses adwaita or something like that (so the text is invisible on background windows)
3. Some icons missing in menus. I don't understand what could be the issue here as not all icons are missing, some display fine (e.g. in the Applications menu all the icons present, while in the System menu only a part of them)
![output](https://user-images.githubusercontent.com/17829319/161330360-9ed9bbea-3fc7-448b-9ef0-958e45d35304.png)
![output2](https://user-images.githubusercontent.com/17829319/161330379-74e66e8d-2a82-4203-a40a-09b7c12648b9.png)

**Comment by wmww** [comment] 2022-04-01 20:05
> The top panel doesn't have background. Should I report this to gtk-layer-background or to mate-panel?

I just tested gtk-layer-demo under wayland-debug, and observer
```
zwlr_layer_surface_v1@23a.set_exclusive_zone(zone=0)
```
To stretch to the edges even when there are exclusive surfaces (such as panels), it should be `-1`. I just fixed this here: https://github.com/wmww/gtk-layer-background/commit/45f869a294a93a92a5648e062ad92eaf5237fb11

However, Mir doesn't yet respect this: https://github.com/MirServer/mir/issues/1992. That should be a reasonable but non-negligible amount of work, so it probably wont happen immediately.

**Comment by wmww** [comment] 2022-04-01 20:08
All the other problems you mention (theme and icons) are due to the mate-wayland snap packaging. Packaging a DE in a snap is a PITA. mate-wayland is an easy to install demo that *something* works, but to make it good would take more work that I had or currently have for it. I recommend either forking the snap so you can tweak it, or installing and/or compiling what you want without screwing with the snap if you want a better experience.

**Comment by ilya-fedin** [comment] 2022-04-01 20:14
I don't use mate-wayland snap, I wrote a NixOS module, packaged mir/mirco/gtk-layer-background, ported mate-wayland snap's startup script, rebuilt mate-panel with in-process applets and patched mate-session-manager/mate-settings-daemon with `gdk_set_allowed_backends("x11");` (to use mate-session's autostart mechanism and have theming with X application from mate-settings-daemon). Theming works fine everywhere (I've set gsettings parameters that gtk reads on Wayland) except of those two places. And I can't find how to set cursor theme for mirco (all apps respect my cursor theme, but mirco's decorations for X applications don't)...

**Comment by ilya-fedin** [comment] 2022-04-01 20:23
That's how it looks like:
https://github.com/ilya-fedin/nur-repository/blob/master/modules/mate-wayland/default.nix
https://github.com/ilya-fedin/nur-repository/blob/master/overlays/mate-wayland/default.nix

**Comment by wmww** [comment] 2022-04-01 20:40
In that case I don't know why GTK themes and icons aren't working. mate-panel should be the same as a normal GTK app in the ways relevant to those things. Perhaps it's being launched in an environment where the needed variables aren't set up yet?

lmao at first glance the reason Mir isn't respecting your cursor theme appears to be be because it's hard-coded [here](https://github.com/MirServer/mir/blob/main/src/server/input/default-theme.h).

**Comment by ilya-fedin** [comment] 2022-04-01 20:46
> Perhaps it's being launched in an environment where the needed variables aren't set up yet?

The icons shouldn't work at all in mate-panel then, I guess? But they do work, just not all of them... And menus are looking like Adapta, while the task switcher looks like Adwaita... And the Applications/Places/System labels have the correct color from Adapta (rather than the task switcher that uses colors from Adwaita)... Task switcher seem to be the only place that uses Adwaita (and AFAIK it's the only part that has completely another implementation on Wayland). The X session works just fine even though it's launched in the same manner (with the same display manager). The only thing that is different on Wayland is an additional wrapper that launches mirco before mate-session.

**Comment by ilya-fedin** [comment] 2022-04-01 20:48
> lmao at first glance the reason Mir isn't respecting your cursor theme appears to be be because it's hard-coded [here](https://github.com/MirServer/mir/blob/main/src/server/input/default-theme.h).

meh :(

**Comment by ilya-fedin** [comment] 2022-04-01 21:02
I didn't want to say that until I update to actual mir, but I've updated and it's still present... Clipboard in XWayland applications is broken. I can paste only one or two times and then Ctrl+V or the context menu item does nothing.
